export const slides = [
    {   description: "Massimo Dutti was founded in 1985 and was acquired by Inditex in 1991. It now has over 643 stores in more than 78 markets and an online presence in 215 markets.The brand was originally aimed at men's fashion. Starting in 1995, women’s fashion was launched in all its dimensions: from the most urban lines to the more casual. Massimo Dutti has consolidated at all levels as a group with national and international growth and has reached over10,000 employees today.Since September 2006, Massimo Dutti has been fully designing and marketing the following lines: Women: Womenswear, Accessories, Fragrances for Men: Menswear, Accessories, Personal Tailoring, Fragrances. Massimo Dutti is a 1985 launched Spanish high-end clothing manufacturing company. It is owned by the Inditex Group, which acquired the brand in 1991 and also owns Zara, Pull & Bear, Bershka, Zara Home and Uterqüe. The headquarters of Massimo Dutti are in Barcelona, Spain. Massimo Dutti has 750 stores in over 74 countries that are part of Africa, North and South America, Asia and Europe. Massimo Dutti opened its first store in India in New Delhi in 2016.",
        image: "imageOne.jpg" 
    },

    { description: "Massimo Dutti was founded in 1985 and was acquired by Inditex in 1991. It now has over 643 stores in more than 78 markets and an online presence in 215 markets.The brand was originally aimed at men's fashion. Starting in 1995, women’s fashion was launched in all its dimensions: from the most urban lines to the more casual. Massimo Dutti has consolidated at all levels as a group with national and international growth and has reached over10,000 employees today.Since September 2006, Massimo Dutti has been fully designing and marketing the following lines: Women: Womenswear, Accessories, Fragrances for Men: Menswear, Accessories, Personal Tailoring, Fragrances. Massimo Dutti is a 1985 launched Spanish high-end clothing manufacturing company. It is owned by the Inditex Group, which acquired the brand in 1991 and also owns Zara, Pull & Bear, Bershka, Zara Home and Uterqüe. The headquarters of Massimo Dutti are in Barcelona, Spain. Massimo Dutti has 750 stores in over 74 countries that are part of Africa, North and South America, Asia and Europe. Massimo Dutti opened its first store in India in New Delhi in 2016.",
        image: "imageTwo.jpg"
    },

    {
        description: "Massimo Dutti was founded in 1985 and was acquired by Inditex in 1991. It now has over 643 stores in more than 78 markets and an online presence in 215 markets.The brand was originally aimed at men's fashion. Starting in 1995, women’s fashion was launched in all its dimensions: from the most urban lines to the more casual. Massimo Dutti has consolidated at all levels as a group with national and international growth and has reached over10,000 employees today.Since September 2006, Massimo Dutti has been fully designing and marketing the following lines: Women: Womenswear, Accessories, Fragrances for Men: Menswear, Accessories, Personal Tailoring, Fragrances. Massimo Dutti is a 1985 launched Spanish high-end clothing manufacturing company. It is owned by the Inditex Group, which acquired the brand in 1991 and also owns Zara, Pull & Bear, Bershka, Zara Home and Uterqüe. The headquarters of Massimo Dutti are in Barcelona, Spain. Massimo Dutti has 750 stores in over 74 countries that are part of Africa, North and South America, Asia and Europe. Massimo Dutti opened its first store in India in New Delhi in 2016.",
        image: "imageThree.jpg",
    },

    {
        description: "Massimo Dutti was founded in 1985 and was acquired by Inditex in 1991. It now has over 643 stores in more than 78 markets and an online presence in 215 markets.The brand was originally aimed at men's fashion. Starting in 1995, women’s fashion was launched in all its dimensions: from the most urban lines to the more casual. Massimo Dutti has consolidated at all levels as a group with national and international growth and has reached over10,000 employees today.Since September 2006, Massimo Dutti has been fully designing and marketing the following lines: Women: Womenswear, Accessories, Fragrances for Men: Menswear, Accessories, Personal Tailoring, Fragrances. Massimo Dutti is a 1985 launched Spanish high-end clothing manufacturing company. It is owned by the Inditex Group, which acquired the brand in 1991 and also owns Zara, Pull & Bear, Bershka, Zara Home and Uterqüe. The headquarters of Massimo Dutti are in Barcelona, Spain. Massimo Dutti has 750 stores in over 74 countries that are part of Africa, North and South America, Asia and Europe. Massimo Dutti opened its first store in India in New Delhi in 2016.",
        image: "imageFour.jpg"
    },

    {
        description: "Massimo Dutti was founded in 1985 and was acquired by Inditex in 1991. It now has over 643 stores in more than 78 markets and an online presence in 215 markets.The brand was originally aimed at men's fashion. Starting in 1995, women’s fashion was launched in all its dimensions: from the most urban lines to the more casual. Massimo Dutti has consolidated at all levels as a group with national and international growth and has reached over10,000 employees today.Since September 2006, Massimo Dutti has been fully designing and marketing the following lines: Women: Womenswear, Accessories, Fragrances for Men: Menswear, Accessories, Personal Tailoring, Fragrances. Massimo Dutti is a 1985 launched Spanish high-end clothing manufacturing company. It is owned by the Inditex Group, which acquired the brand in 1991 and also owns Zara, Pull & Bear, Bershka, Zara Home and Uterqüe. The headquarters of Massimo Dutti are in Barcelona, Spain. Massimo Dutti has 750 stores in over 74 countries that are part of Africa, North and South America, Asia and Europe. Massimo Dutti opened its first store in India in New Delhi in 2016.",
        image: "imageFive.jpg"
    },

    {
        description: "Massimo Dutti was founded in 1985 and was acquired by Inditex in 1991. It now has over 643 stores in more than 78 markets and an online presence in 215 markets.The brand was originally aimed at men's fashion. Starting in 1995, women’s fashion was launched in all its dimensions: from the most urban lines to the more casual. Massimo Dutti has consolidated at all levels as a group with national and international growth and has reached over10,000 employees today.Since September 2006, Massimo Dutti has been fully designing and marketing the following lines: Women: Womenswear, Accessories, Fragrances for Men: Menswear, Accessories, Personal Tailoring, Fragrances. Massimo Dutti is a 1985 launched Spanish high-end clothing manufacturing company. It is owned by the Inditex Group, which acquired the brand in 1991 and also owns Zara, Pull & Bear, Bershka, Zara Home and Uterqüe. The headquarters of Massimo Dutti are in Barcelona, Spain. Massimo Dutti has 750 stores in over 74 countries that are part of Africa, North and South America, Asia and Europe. Massimo Dutti opened its first store in India in New Delhi in 2016.",
        image: "imageSix.jpg"
    }
]